### ISSUE TITLE
Mapping to multiple zeal languages

### ISSUE THREAD

**Issue by DannyBen** [vaanwd/Zeal#13]
I am trying to figure out what is the way to map the same language to several Zeal languages.

For example, map Ruby to both "Ruby" and "Ruby on Rails".

This is what I guessed so far:

```
    "Ruby": {"lang": "ruby", "zeal_lang": "ruby 2"},
    "Ruby": {"lang": "ruby", "zeal_lang": "ruby on rails 4"},
```

(Excellent plugin and application btw)

EDIT:

Ok - I think I figured it out. Had to use a different key, and then sublime opens a menu to choose from:

```
    "Ruby": {"lang": "ruby", "zeal_lang": "ruby 2"},
    "Rails": {"lang": "ruby", "zeal_lang": "ruby on rails 4"},
```

Is that right?

**Comment by AlexVPopov** [comment]
@DannyBen I don't know if this is the "correct" way, but it works well, so thank you :+1: :smile:

**Comment by mehdilamaaffar** [comment]
thanks its works !

**Comment by kafene** [comment]
You can also use 

   "Ruby": {"lang": "ruby", "zeal_lang": "ruby 2,ruby on rails 4"},
    
Well I think that will work, I'm using this successfully

    "JavaScript": {"lang": "javascript", "zeal_lang": "javascript,jQuery"},
