### ISSUE TITLE
Language mapping not working (C++)

### ISSUE THREAD

**Issue by gnoweb** [vaanwd/Zeal#16]
After I press F1 in a .cpp file, why it say "No Zeal mapping was found for c language." ?
How to fix this problem?

Have I set something wrong?
____________________________________________

{
  "zeal_command": "E:\\Software\\Programming\\Zeal\\zeal.exe",

  "mapping_sort" : true,

  "language_mapping": {
    "HTML": {"lang": "html", "zeal_lang": "html"},
    "JavaScript": {"lang": "javascript", "zeal_lang": "javascript"},
    "CSS": {"lang": "css", "zeal_lang": "css"},
    "PHP": {"lang": "php", "zeal_lang": "php"},
    "Python": {"lang": "python", "zeal_lang": "python"},
    "C++": {"lang": "c++", "zeal_lang": "c++"}    /* Is this correct?  <<<<<<<<<<<<<<<<<<<<<<<<<<< */
  }
}

**Comment by gnoweb** [comment]
I have found a way to fix it, but not perfect:
___________________________________

{

  "zeal_command": "E:\\Software\\Programming\\Zeal\\zeal.exe",

  "mapping_sort" : true,

  "language_mapping": {
    "HTML": {"lang": "html", "zeal_lang": "html"},
    "JavaScript": {"lang": "javascript", "zeal_lang": "javascript"},
    "CSS": {"lang": "css", "zeal_lang": "css"},
    "PHP": {"lang": "php", "zeal_lang": "php"},
    "Python": {"lang": "python", "zeal_lang": "python"},
    "C++": {"lang": "c", "zeal_lang": "c++"},
    "C": {"lang": "c", "zeal_lang": "c"}
  }
}

**Comment by HustLion** [comment]
Thanks a lot. This works.
