### ISSUE TITLE
--query command not supported anymore by Zeal 0.3.0

### ISSUE THREAD

**Issue by lechat69** [vaanwd/Zeal#21]
Form Zeal 0.3.0 : Dropped support for --query command line parameter.

https://github.com/zealdocs/zeal/releases/tag/v0.3.0

**Comment by FichteFoll** [comment]
Apparently it has been deprecated [over a year ago](https://github.com/zealdocs/zeal/commit/4345697e0e1d208aa694b08440418f47ff747ca4), so it should be save to drop it completely in this code.

**Comment by dwells** [comment]
Changing zeal.py line 162 to remove the "--query" option is working for me. Though @Kristinita 

Old zeal.py line 162:
`cmd = [zeal_exe, u"--query"]`

New zeal.py line 162: 
` cmd = [zeal_exe]`

**Comment by Kristinita** [comment]
@dwells, I need manually print my query in Zeal:

![Zeal Manually](http://i.imgur.com/h0Gmp8Q.gif)

### Environment

**Operating system and version:**
Windows 10.0.14393
**Sublime Text:**
Build 3126
**Zeal:**
Version 0.3.0

Thanks.

**Comment by dwells** [comment]
@Kristinita what happens when you place the cursor in your query word in Sublime then press F1 or right click and select Search Zeal?

**Comment by Kristinita** [comment]
@dwells , exactly the same behavior. Thanks.

**Comment by ianchanning** [comment]
@dwells My attempts at changing `zeal.py` locally failed too. I closed ST3, went into the `%APPDATA%\Sublime Text 3\Installed Packages` directory. There I extracted the `Zeal.sublime-package` and edited the `zeal.py` file, and edited line 162 as you suggested. I then rezipped that up and replaced the original `Zeal.sublime-package` with the modified one.

However this doesn't work with my Sublime Text, nothing happens with <kbd>F1</kbd> and the right-click option to 'Search Zeal' is greyed out.

**Comment by ianchanning** [comment]
Note that my workaround is basically just to downgrade Zeal. I don't need any of the new features. The issue is of course that there's no direct links to the 0.2.1 download any more. However it is still available from the same directory as 0.3.0 that is:

https://dl.bintray.com/zealdocs/windows/zeal-0.2.1-windows-x86.msi

**Comment by dwells** [comment]
@ianchanning sorry to hear that didn't work for you.  I cloned the most recent version of the project in my `Data\Packages` directory then edited the file directly. I read that Zeal 3 is faster but I haven't noticed any big difference yet.

I can't reproduce the issue but here are my testing steps in case it helps someone else: 
With the change I described made, saved, and Sublime restarted, I place the cursor on the word 'append' in zeal.py in Sublime (any source file will do) and press `F1` and Zeal runs with python:append in the query input box. I add a `print()` command before `subprocess.Popen()` to output the cmd value to Sublime's console and the value of cmd is ['C:\\Program Files (x86)\\Zeal\\zeal.exe', 'python:append']. When I run `"C:\Program Files (x86)\Zeal\zeal.exe" python:append` Zeal runs with python:append in the query input box. Hope that helps your debugging.

**Comment by ianchanning** [comment]
@dwells All I can think of is that I am installing via the package manager rather than with the raw source. That is I'm editing the zip file in `Installed Packages` rather than raw source in `Packages`. I'm guessing that there might be some kind of MD5 checking that I violate when I mess around with the zipped up package which effectively deactivates the package.

**Comment by FichteFoll** [comment]
There is no such checking, but the recommended way is to create an override package for the zeal.py file. See http://docs.sublimetext.info/en/latest/extensibility/packages.html#customizing-or-overriding-packages.

**Comment by dwells** [comment]
@ianchanning and @Kristinita - What is the value of `cmd` when you run it? Does the same command work when you copy and paste it to a command line?

**Comment by Kristinita** [comment]
@dwells,

### Steps to reproduce

I install new 0.3.1 portable version Zeal → I add `E:\Zeal\` to my user variable `PATH` → I remove `--query` option from `zeal.py` file.

I select element of syntax computer language → <kbd>Ctrl+Shift+P</kbd> → `Zeal: Search Selection` → query not add in Zeal input area. But if I make my query again, all works good.

If I print my commands in command line I get same behavior. Queries works correct only the second time. Perhaps this is Zeal bug.

### Summary

Queries works correct only if `Zeal.exe` is enabled. But `Zeal.exe` takes >110 Mb in RAM. I don't want add Zeal to Startup.

Thanks.
