### ISSUE TITLE
option to be able to deactivate language specific search mapping

### ISSUE THREAD

**Issue by eikaramba** [vaanwd/Zeal#7]
Hey, first of all thx for this great plugin. Works great, but there is one problem.

In any javascript file, if i want to search with F1 for a specific method, and this method is e.g. a lodash method, he adds the javascript prefix to the search query. Now this is normally a good option, but as javascript can be used with many libs and each one might have its own documentation i think it would be cool to disable this language agnostic option.

something like
"language_mapping": {
    "JavaScript": {activated:false}
  }
so that in any javascript files he now searches just for the term under the cursor

**Comment by Patabugen** [comment]
I'd also like to be able to disable the mappings, specially in my case it's loading WordPress function docs from within a "php" file.

I don't have so many doc-sets that not filtering by language will ever cause a real problem - I'd like to be able to globally disable it.

One possible method would be to put an empty string in the language mapping, this currently almost works except for still including the colon - so if the plugin just didn't add the colon if the zeal_lang is empty it would work.

```
  "language_mapping": {
    "HTML": {"lang": "html", "zeal_lang": ""},
  }
```
